export const surprisePrompts = [
    "A peaceful mountain landscape",
    "A futuristic cityscape",
    "A dreamy underwater scene",
    "A magical forest with glowing mushrooms",
    "A cozy cottage in the woods",
    "A surreal landscape with floating islands",
    "A majestic castle on a hill",
    "A post-apocalyptic wasteland",
    "A sci-fi space station",
    "A whimsical carnival with flying pigs",
    "A haunting ghost town",
    "A beautiful sunset over the ocean",
    "An enchanted garden with talking animals",
    "A vibrant jungle with exotic animals",
    "A dark and stormy night",
    "A peaceful countryside with grazing sheep",
    "A futuristic flying car",
    "A mystical dragon in a cave",
    "A spooky haunted house",
    "A serene lake with a reflection of the mountains",
    "A futuristic robot city",
    "A magical unicorn in a meadow",
    "A desert oasis",
    "A bustling city street",
    "A serene garden with a koi pond",
    "A majestic elephant in the wild",
    "A cozy coffee shop on a rainy day",
    "A magical mermaid in the ocean",
    "A futuristic cyberpunk city",
    "A beautiful butterfly garden",
    "A snowy winter wonderland",
    "A prehistoric jungle with dinosaurs",
    "A peaceful village in the countryside",
    "A mysterious floating city",
    "A beautiful cherry blossom garden",
    "A futuristic hovercraft",
    "A majestic lion in the savannah",
    "A whimsical fairy tale castle",
    "A tranquil river flowing through a forest",
    "A creepy abandoned asylum",
    "A stunning aurora borealis in the sky",
    "A futuristic underwater city",
    "A magical genie in a lamp",
    "A serene Zen garden",
    "A futuristic hoverboard",
    "A majestic horse in the wild",
    "A cozy bookstore with a fireplace",
    "A mystical phoenix in flight",
    "A futuristic spacecraft",
    "A beautiful peacock garden",
    "A creepy abandoned amusement park",
    "A stunning sunset over the city",
    "A mystical crystal cave",
    "A futuristic hoverbike",
    "A majestic tiger in the jungle",
    "A cozy cabin in the mountains",
    "A beautiful rainbow over the hills",
    "A futuristic laser gun",
    "A mystical unicorn forest",
    "A serene waterfall in the woods",
    "A creepy abandoned factory",
    "A stunning galaxy in outer space",
    "A futuristic jetpack",
    "A majestic wolf in the wild",
    "A cozy fireplace in a cabin",
    "A mystical genie lamp in a desert",
    "A futuristic drone",
    "A beautiful garden with a fountain",
    "A creepy abandoned church",
    "A stunning starry night sky",
    "A mystical fairy forest",
    "A serene beach with palm trees",
    "A futuristic laser sword",
    "A majestic eagle in the sky",
    "A cozy library with books",
    "A mystical genie palace",
    "A futuristic robot dog",
    "A beautiful garden with a gazebo",
    "A creepy abandoned mansion",
    "A stunning city skyline at night",
    "A mystical dragon castle",
];